services:
  - type: web
    name: aplicativo-web-finanzas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG_SHOW_OTP_IN_CONSOLE
        value: "False"
      - key: SMTP_SERVER
        fromEnvVar: SMTP_SERVER
      - key: SMTP_PORT
        fromEnvVar: SMTP_PORT
      - key: SMTP_USER
        fromEnvVar: SMTP_USER
      - key: SMTP_PASS
        fromEnvVar: SMTP_PASS
